---
development:
  cloud_name: name
  api_key: 'key'
  api_secret: secret
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: name
  api_key: 'key'
  api_secret: secret
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: name
  api_key: 'key'
  api_secret: secret
  enhance_image_tag: true
  static_image_support: false
