---
:pm_bonus_coefficients:
  :base_percent: 4
  :verbal_complaints: -100
  :written_complaints: -250
  :letters_of_thanks: 500
  :deadline_bonus_coefficients:
    :pm_ahead_of_schedule: 1.5
    :pm_in_time: 1
    :pm_delayed_by_2_weeks_fault_customer: 1
    :pm_delayed_by_2_weeks_fault_company: -0.5
    :pm_delayed_by_4_weeks_fault_company: -1
